### ISSUE TITLE
Control code cell visibility and behavior with tags and metadata 

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mystmd#1108]
Currently, all code cells that are parsed by MyST will include their input and outputs together.

Outputs can be inserted into the page via the `{embed}` directive, which allows you to remove the input, output, or include both.

However it's not possible to modify the behavior of the code cell itself, which makes it clunky if you want the code cell to exist on the same page where you want to embed its output.

It would be helpful if there were a way to control the visibility of the cell input and cell output from within a code cell.

### How MyST-NB handles this

MyST NB accomplishes this by [using Cell Metadata tags](https://myst-nb.readthedocs.io/en/latest/configuration.html#cell-tags), with tags like the following:

- `remove-cell`
- `remove-input`
- `remove-output`
- `hide-input` (hides behind a toggle)
- `hide-output`
- `skip-execution`
- `raises-exception` (to prevent errors from stopping the build process)

**Comment by rowanc1** [comment]
This was partially implemented here:

https://github.com/executablebooks/mystmd/pull/407

But I believe is undocumented on our side. I think at this stage, only the `remove-cell/input/output` is respected (no toggles). The tags are listed here:

https://github.com/executablebooks/mystmd/blob/main/packages/myst-common/src/types.ts#L34

There was an initial PR on this in the theme over here:
- https://github.com/executablebooks/myst-theme/pull/129
- Related issue: https://github.com/executablebooks/myst-theme/issues/50

We got the first part merged, but not the theme as there were changes to thebe that we needed to consider.

**Comment by choldgraf** [comment]
Ah nice - I've added a PR to document some of this here:

#1110 

Agreed that there's still functionality that needs to be added, so we can use this to flesh out the behavior.

**Comment by drewlio** [comment]
Sorry to bother you, but it seems `remove-cell/input/output` tags are not respected for PDF output for native jupyter code cells. From looking at https://github.com/executablebooks/mystmd/pull/407 it seems like it should work [just as it does in Jupyter Book](https://jupyterbook.org/en/stable/interactive/hiding.html). It seems like #407 was merged at 1.0.2. I'm on 1.2.0. I'm not sure why its not working.

**Comment by agahkarakuzu** [comment]
I am running into a similar issue (`v1.2.3`), where `remove-input` works, but `hide-input` does not. Not sure if this is not implemented yet, but interestingly, it throws a warning when you pass both tags.

**Comment by agoose77** [comment]
@drewlio this should have been fixed in 1.3.3. Would you be able to check that for me? :)

**Comment by agoose77** [comment]
> I am running into a similar issue (`v1.2.3`), where `remove-input` works, but `hide-input` does not. Not sure if this is not implemented yet, but interestingly, it throws a warning when you pass both tags.

@agahkarakuzu could you possibly provide a reproducer?

**Comment by agahkarakuzu** [comment]
@agoose77 I'll soon test this, sorry for the late reply!

**Comment by agahkarakuzu** [comment]
@agoose77 versions are the following: 

```
[2024-09-10 01:55:19,833: WARNING/ForkPoolWorker-7] ✓ Node.js is installed: v22.6.0
[2024-09-10 01:55:20,836: WARNING/ForkPoolWorker-7] ✓ mystmd is installed: v1.3.8
```

### 1. Hide input issue still persists. 

For example, the first code block of [this notebook](https://preview2.neurolibre.org/myst/agahkarakuzu/mriscope/c6cca3ce5d0b12417883fb81b338a317e58d2fec/_build/html/literature-overview#main) of [this myst article](https://preview2.neurolibre.org/myst/agahkarakuzu/mriscope/c6cca3ce5d0b12417883fb81b338a317e58d2fec/_build/html) has the `hide-input` set true, yet the code cell is still visible with no toggle option.

### 2. Interactive figure outputs are generated, but not embedded

[This 3D interactive plot](https://preview2.neurolibre.org/myst/agahkarakuzu/mriscope/c6cca3ce5d0b12417883fb81b338a317e58d2fec/_build/html/build/6a98215996ba59ce5736b64e39e28cb7.html) was generated during `myst build` (with execute), but does not show up in the myst article. 

### 3. Default article-theme dark?

I used to build articles with light-theme, but now by default it is dark, how can I set this back to light?

**Comment by cpraveen** [comment]
`hide-input` is a really nice option that I would love to have.
